Repository rust-embedded/wg, pull requests merged in 2018-08, with the labels that each got.

#145 move out the embedonomicon
  books/embedonomicon/.gitignore
  books/embedonomicon/LICENSE-APACHE
  books/embedonomicon/LICENSE-CC-BY-SA
  books/embedonomicon/LICENSE-MIT
  books/embedonomicon/README.md
  books/embedonomicon/book.toml
  books/embedonomicon/src/SUMMARY.md
  books/embedonomicon/src/before-main.md
  books/embedonomicon/src/cargo-config.md
  books/embedonomicon/src/exceptions.md
  books/embedonomicon/src/exceptions/provide.md
  books/embedonomicon/src/exceptions/struct.md
  books/embedonomicon/src/exceptions/weak.md
  books/embedonomicon/src/glue-crate.md
  books/embedonomicon/src/interlude-i.md
  books/embedonomicon/src/interlude-ii.md
  books/embedonomicon/src/less-unstable.md
  books/embedonomicon/src/less-unstable/asm.md
  books/embedonomicon/src/less-unstable/start.md
  books/embedonomicon/src/less-unstable/used.md
  books/embedonomicon/src/less-unstable/weak.md
  books/embedonomicon/src/linker-scripts.md
  books/embedonomicon/src/linking.md
  books/embedonomicon/src/memory.md
  books/embedonomicon/src/modular-linker-scripts.md
  books/embedonomicon/src/no-std-binary.md
  books/embedonomicon/src/panic-fmt.md
  books/embedonomicon/src/preface.md
  books/embedonomicon/src/start.md
  books/embedonomicon/src/vector-table.md
Labels: T-resources

#191 [RFC] blog.rust-embedded.org
  rfcs/0000-blog.md
Labels: T-resources

#172 IRC Operational Notes
  ops/irc.md
Labels: RFC

#187 [RFC] Embedded Rust Showcase
  rfcs/0000-embedded-rust-showcase.md
Labels: RFC, T-resources, needs-decision
